"""Generate editable KiCad PCB, routed preview and a labelled connection schematic.

R0 prototype: router output must undergo KiCad DRC and module fit verification.
No manufacturing Gerbers are generated by this script.
"""
import csv
import heapq
import html
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "public/downloads"
DESIGN = json.loads((ROOT / "public/design.json").read_text())
PAD_SIZE = 1.8
PADS = []

def pad(ref, number, name, net, x, y, size=PAD_SIZE, drill=.9):
    PADS.append(dict(ref=ref, number=str(number), name=name, net=net,
                     x=round(x, 4), y=round(y, 4), size=size, drill=drill))

left = ["3V3","EN","VP","VN","IO34","IO35","IO32","IO33","IO25","IO26","IO27","IO14","IO12","GND","IO13","D2","D3","CMD","5V"]
right = ["GND","IO23","IO22","TX","RX","IO21","GND","IO19","IO18","IO5","IO17","IO16","IO4","IO0","IO2","IO15","D1","D0","CLK"]
net_by_name = {"3V3":"+3V3", "GND":"GND", "5V":"+5V_ESP", "IO25":"E32_M0", "IO26":"E32_TXD", "IO27":"E32_RXD", "IO19":"E32_AUX", "IO18":"E32_M1", "IO17":"GPS_RX", "IO16":"GPS_TX", "IO2":"LED_GPIO"}
for ref, x, names in [("J2",8,left),("J3",33.4,right)]:
    for i,name in enumerate(names):
        pad(ref,i+1,name,net_by_name.get(name,""),x,25+i*2.54)
for i,(name,net) in enumerate([("VCC","+3V3"),("RX","GPS_RX"),("TX","GPS_TX"),("GND","GND")]):
    pad("JGPS",i+1,name,net,42.5+i*2.54,43)
for i,net in enumerate(["E32_M0","E32_M1","E32_RXD","E32_TXD","E32_AUX","+5V_MAIN","GND"]):
    pad("JE32",i+1,net.replace("E32_",""),net,74.38+i*2.54,51.5)
pad("JPOWER",1,"5V IN","+5V_MAIN",70,71,2.6,1.2)
pad("JPOWER",2,"GND","GND",75.08,71,2.6,1.2)
pad("JP1",1,"ESP5V","+5V_ESP",58,65)
pad("JP1",2,"MAIN5V","+5V_MAIN",60.54,65)
pad("C1",1,"+","+5V_MAIN",78,66,2,1)
pad("C1",2,"-","GND",82,66,2,1)
pad("C2",1,"1","+5V_MAIN",88,65,1.2,0)
pad("C2",2,"2","GND",90,65,1.2,0)
pad("R1",1,"1","LED_GPIO",42,65,1.2,0)
pad("R1",2,"2","LED_A",44,65,1.2,0)
pad("D1",1,"A","LED_A",48,65,1.2,0)
pad("D1",2,"K","GND",50,65,1.2,0)
NETS = sorted({p["net"] for p in PADS if p["net"]})
TRACES, VIAS = [], []

# Grid router: both copper layers; vias are penalised. Conservative circular
# pad envelopes and trace clearance account for endpoint grid snapping.
STEP = .25
NX, NY = 401, 313
CLEARANCE = .25

def cell(x,y): return (round(x/STEP),round(y/STEP))

def block_disk(blocked,x,y,r,layers=(0,1)):
    x0,y0 = cell(x,y)
    n = math.ceil(r/STEP)+1
    for dx in range(-n,n+1):
        for dy in range(-n,n+1):
            if (dx*STEP)**2+(dy*STEP)**2 <= (r+.18)**2:
                for layer in layers: blocked.add((x0+dx,y0+dy,layer))

def obstacles(net,width):
    blocked=set()
    for p in PADS:
        if p["net"] != net:
            block_disk(blocked,p["x"],p["y"],p["size"]/2+width/2+CLEARANCE)
    for x,y in DESIGN["board"]["holes"]:
        block_disk(blocked,x,y,1.6+width/2+CLEARANCE)
    for t in TRACES:
        if t["net"] == net: continue
        for (x1,y1),(x2,y2) in zip(t["points"],t["points"][1:]):
            n=max(1,math.ceil(math.hypot(x2-x1,y2-y1)/STEP))
            for i in range(n+1):
                block_disk(blocked,x1+(x2-x1)*i/n,y1+(y2-y1)*i/n,
                           t["width"]/2+width/2+CLEARANCE,(0 if t["layer"]=="F.Cu" else 1,))
    for via in VIAS:
        if via["net"]!=net: block_disk(blocked,via["x"],via["y"],.4+width/2+CLEARANCE)
    return blocked

def route(a,b,net,width):
    blocked=obstacles(net,width)
    sx,sy=cell(a["x"],a["y"]);tx,ty=cell(b["x"],b["y"])
    starts={(sx,sy,l) for l in ([0,1] if a["drill"] else [0])}
    queue=[(0,0,s) for s in starts];heapq.heapify(queue);cost={s:0 for s in starts};parent={}
    goal=None
    while queue:
        _,g,at=heapq.heappop(queue)
        if g != cost[at]: continue
        x,y,layer=at
        if (x,y)==(tx,ty) and (b["drill"] or layer==0): goal=at;break
        for dx,dy,dl in [(1,0,0),(-1,0,0),(0,1,0),(0,-1,0),(0,0,1)]:
            nxt=(x+dx,y+dy,layer^dl)
            xx,yy,ll=nxt
            if not(4<=xx<NX-4 and 4<=yy<NY-4): continue
            # ESP32 PCB antenna keepout, both layers.
            if 4<=xx*STEP<=36 and yy*STEP<24: continue
            if nxt in blocked: continue
            if dl:
                # Via clearance must be valid on both layers, not just the destination.
                if any((xx+vx,yy+vy,vl) in blocked for vx in [-2,-1,0,1,2] for vy in [-2,-1,0,1,2] for vl in [0,1]): continue
            ng=g+(30 if dl else 1)
            if ng>=cost.get(nxt,math.inf): continue
            cost[nxt]=ng;parent[nxt]=at
            h=abs(xx-tx)+abs(yy-ty)
            heapq.heappush(queue,(ng+h,ng,nxt))
    if goal is None: raise RuntimeError(f"Cannot route {net}: {a} → {b}; start blocked {[s in blocked for s in starts]}, goal blocked {[(tx,ty,l) in blocked for l in [0,1]]}; explored {len(cost)}")
    path=[goal]
    while path[-1] not in starts:path.append(parent[path[-1]])
    path.reverse()
    # Keep bends only; exact pad centres at the first and last endpoint.
    layer=path[0][2];points=[[a["x"],a["y"]],[sx*STEP,sy*STEP]]
    for prev,cur in zip(path,path[1:]):
        x,y,ll=cur
        if ll!=layer:
            points.append([x*STEP,y*STEP]);store_trace(net,width,layer,points)
            VIAS.append(dict(x=x*STEP,y=y*STEP,net=net))
            layer=ll;points=[[x*STEP,y*STEP]]
        else:points.append([x*STEP,y*STEP])
    points.append([b["x"],b["y"]]);store_trace(net,width,layer,points)

def store_trace(net,width,layer,points):
    clean=[]
    for p in points:
        if clean and p==clean[-1]:continue
        if len(clean)>=2:
            ax,ay=clean[-2];bx,by=clean[-1];cx,cy=p
            if abs((bx-ax)*(cy-by)-(by-ay)*(cx-bx))<1e-9:clean.pop()
        clean.append(p)
    if len(clean)>1:TRACES.append(dict(net=net,width=width,layer="F.Cu" if layer==0 else "B.Cu",points=clean))

def generate():
    OUT.mkdir(parents=True,exist_ok=True)
    import random
    presets=[['LED_GPIO','LED_A','+5V_ESP','+5V_MAIN','GND','+3V3'],
             ['+5V_ESP','+5V_MAIN','GND','+3V3','LED_GPIO','LED_A'],
             ['GND','+5V_MAIN','+5V_ESP','+3V3','LED_GPIO','LED_A']]
    rng=random.Random(42)
    for attempt in range(20):
        TRACES.clear();VIAS.clear()
        if attempt<len(presets):order=presets[attempt]+[n for n in NETS if n not in presets[attempt]]
        else:order=NETS[:];rng.shuffle(order)
        try:
            for net in order:
                group=[p for p in PADS if p["net"]==net]
                connected=[group.pop(0)]
                while group:
                    pairs=[(math.hypot(a["x"]-b["x"],a["y"]-b["y"]),i,a,b) for i,b in enumerate(group) for a in connected]
                    _,i,a,b=min(pairs,key=lambda t:t[0])
                    route(a,b,net,.8 if net.startswith("+5") or net=="GND" else .35)
                    connected.append(group.pop(i))
            print("All nets routed; order:",order,flush=True);break
        except RuntimeError as error:
            print("Retry",attempt+1,str(error).split(';')[0],flush=True)
    else:raise RuntimeError("No complete route after 20 deterministic attempts")
    data=dict(pads=PADS,traces=TRACES,vias=VIAS,nets=NETS,clearance=CLEARANCE,status="R0 / DRC pending")
    (ROOT/"public/pcb.json").write_text(json.dumps(data,indent=2)+"\n")
    write_kicad()
    write_schematic()
    write_bom()

def write_kicad():
    net_ids={n:i+1 for i,n in enumerate(NETS)}
    text=['(kicad_pcb (version 20240108) (generator "alanatech-code")',
          '(general (thickness 1.6))','(paper "A4")',
          '(layers (0 "F.Cu" signal) (31 "B.Cu" signal) (36 "B.SilkS" user "b.silkscreen") (37 "F.SilkS" user "f.silkscreen") (38 "B.Mask" user) (39 "F.Mask" user) (44 "Edge.Cuts" user) (48 "B.Fab" user) (49 "F.Fab" user))',
          '(setup (pad_to_mask_clearance 0))','(net 0 "")']
    text += [f'(net {i} "{n}")' for n,i in net_ids.items()]
    values={"J2":"ESP32_J2_1x19","J3":"ESP32_J3_1x19","JGPS":"NEO6M_SOCKET_1x04","JE32":"E32_SOCKET_1x07_RIGHT_ANGLE","JPOWER":"5V_INPUT_2A","JP1":"REMOVE_FOR_USB","C1":"1000uF_10V","C2":"100nF_0805","R1":"330R_0805","D1":"LED_0805"}
    for ref in dict.fromkeys(p["ref"] for p in PADS):
        group=[p for p in PADS if p["ref"]==ref];anchor=group[0];x,y=anchor["x"],anchor["y"]
        text.append(f'(footprint "AlanaTech:{values[ref]}" (layer "F.Cu") (at {x} {y})')
        text.append(f'(fp_text reference "{ref}" (at 0 -2) (layer "F.SilkS") (effects (font (size 1 1) (thickness 0.15))))')
        text.append(f'(fp_text value "{values[ref]}" (at 0 2) (layer "F.Fab") (effects (font (size 1 1) (thickness 0.15))))')
        for p in group:
            nid=net_ids.get(p["net"],0);xx=p["x"]-x;yy=p["y"]-y;s=p["size"]
            if p["drill"]:kind=f'thru_hole circle (at {xx:.4f} {yy:.4f}) (size {s} {s}) (drill {p["drill"]}) (layers "*.Cu" "*.Mask")'
            else:kind=f'smd roundrect (at {xx:.4f} {yy:.4f}) (size {s} {s}) (layers "F.Cu" "F.Mask") (roundrect_rratio 0.2)'
            text.append(f'(pad "{p["number"]}" {kind} (net {nid} "{p["net"]}"))')
        text.append(')')
    for i,(x,y) in enumerate(DESIGN["board"]["holes"]):
        text.append(f'(footprint "MountingHole:M3" (layer "F.Cu") (at {x} {y}) (fp_text reference "H{i+1}" (at 0 -3) (layer "F.SilkS") (effects (font (size 1 1) (thickness 0.15)))) (pad "" np_thru_hole circle (at 0 0) (size 3.2 3.2) (drill 3.2) (layers "*.Cu" "*.Mask")))')
    for t in TRACES:
        for (x1,y1),(x2,y2) in zip(t["points"],t["points"][1:]):
            text.append(f'(segment (start {x1} {y1}) (end {x2} {y2}) (width {t["width"]}) (layer "{t["layer"]}") (net {net_ids[t["net"]]}))')
    for v in VIAS:text.append(f'(via (at {v["x"]} {v["y"]}) (size 0.8) (drill 0.4) (layers "F.Cu" "B.Cu") (net {net_ids[v["net"]]}))')
    text.append('(gr_rect (start 0 0) (end 100 78) (stroke (width 0.05) (type solid)) (fill none) (layer "Edge.Cuts"))')
    text.append('(gr_text "ALANATECH GPS / CARRIER R0 / DRC PENDING" (at 50 5) (layer "F.SilkS") (effects (font (size 1 1) (thickness 0.15))))')
    # Antenna keepout both layers: never route copper under the ESP32 antenna.
    text.append('(zone (net 0) (net_name "") (layers "F.Cu" "B.Cu") (hatch edge 0.5) (connect_pads (clearance 0.25)) (min_thickness 0.25) (keepout (tracks not_allowed) (vias not_allowed) (pads not_allowed) (copperpour not_allowed) (footprints allowed)) (polygon (pts (xy 4 0) (xy 36 0) (xy 36 24) (xy 4 24))))')
    text.append(')')
    (OUT/"carrier.kicad_pcb").write_text("\n".join(text)+"\n")
    # Explicit electrical netlist for reviewing the generated board.
    netlist=['(export (version "D") (design (source "generate_pcb.py")) (components']
    netlist += [f'(comp (ref {ref}) (value "{value}"))' for ref,value in values.items()]
    netlist.append(') (nets')
    for n,nid in net_ids.items():
        nodes=' '.join(f'(node (ref {p["ref"]}) (pin {p["number"]}))' for p in PADS if p["net"]==n)
        netlist.append(f'(net (code {nid}) (name "{n}") {nodes})')
    netlist.append('))');(OUT/"carrier.net").write_text("\n".join(netlist)+"\n")

def write_schematic():
    rows=[("GPS TX → ESP RX","JGPS.3","GPIO16 / J3.12","GPS_TX"),
          ("ESP TX → GPS RX","GPIO17 / J3.11","JGPS.2","GPS_RX"),
          ("E32 TXD → ESP RX","JE32.4","GPIO26 / J2.10","E32_TXD"),
          ("ESP TX → E32 RXD","GPIO27 / J2.11","JE32.3","E32_RXD"),
          ("Режим радио M0","GPIO25 / J2.9","JE32.1","E32_M0"),
          ("Режим радио M1","GPIO18 / J3.9","JE32.2","E32_M1"),
          ("Готовность AUX","JE32.5","GPIO19 / J3.8","E32_AUX"),
          ("Питание GPS","3V3 / J2.1","JGPS.1","+3V3"),
          ("Питание E32","JPOWER.1 / 5V","JE32.6, C1+, C2.1","+5V_MAIN"),
          ("Питание ESP32","5V → JP1 → J2.19","Снять JP1 при USB","+5V_ESP"),
          ("Общая земля","JPOWER.2","J2.14 / J3.1,7 / GPS.4 / E32.7","GND"),
          ("Индикатор TX","GPIO2 / J3.15","R1 330Ω → D1 → GND","LED_GPIO")]
    parts=['<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="690" viewBox="0 0 1000 690"><rect width="1000" height="690" fill="#fafcf7"/><g font-family="Arial, sans-serif" fill="#304837"><text x="40" y="42" font-size="22">ALANATECH GPS · СХЕМА СОЕДИНЕНИЙ R0</text><text x="40" y="68" font-size="12" fill="#84937c">ESP32-DevKitC V4 WROOM · NEO-6M breakout · E32-433T30D</text>']
    for i,(title,a,b,net) in enumerate(rows):
        y=108+i*40
        parts.append(f'<rect x="35" y="{y-20}" width="930" height="35" rx="4" fill="{"#eff4e9" if i%2==0 else "#fafcf7"}"/><text x="48" y="{y}" font-size="12">{html.escape(title)}</text><text x="270" y="{y}" font-size="11">{html.escape(a)}</text><path d="M430 {y-4}h85" stroke="#36896b" stroke-width="2"/><text x="536" y="{y}" font-size="11">{html.escape(b)}</text><text x="895" y="{y}" font-size="9" text-anchor="end" fill="#719168">{html.escape(net)}</text>')
    parts.append('<text x="40" y="622" font-size="12">C1: 1000 µF / 10 V, C2: 100 nF — параллельно 5V_MAIN / GND рядом с E32.</text><text x="40" y="647" font-size="12">Вход: стабилизированные 5 В / 2 А. UART: 3.3 В. Установить антенну до включения радио.</text><text x="40" y="674" font-size="11" fill="#899379">Контакты GPS и механика углового E32-разъёма требуют сверки. DRC/ERC и стендовая проверка ещё не выполнены.</text></g></svg>')
    (OUT/"schematic.svg").write_text("".join(parts))

def write_bom():
    rows=[("U1",1,"ESP32-DevKitC V4 WROOM","38 contacts, 25.4 mm between rows; not WROVER"),
          ("U2",1,"NEO-6M breakout + patch antenna","verify board size and VCC RX TX GND order; 3.3V capable"),
          ("U3",1,"EBYTE E32-433T30D","24 x 43 mm, UART 3.3V, 5V supply"),
          ("J2 J3",2,"Female header 1x19 2.54 mm","through-hole sockets for ESP32"),
          ("JGPS",1,"Female header 1x04 2.54 mm","verify module orientation"),
          ("JE32",1,"Right-angle female header 1x07 2.54 mm","verify pin orientation and horizontal module height"),
          ("JPOWER",1,"Screw terminal 1x02 5.08 mm","5V regulated input, >=2A"),
          ("JP1",1,"Header 1x02 2.54 mm + shunt","disconnect before USB programming"),
          ("C1",1,"1000uF 10V low-ESR electrolytic","diameter <=8 mm height <=12 mm pitch 4 mm"),
          ("C2",1,"100nF X7R 0805",">=10V"),("R1",1,"330 Ohm 0805","LED series resistor"),
          ("D1",1,"Green LED 0805","A/K orientation required"),
          ("ANT",1,"433 MHz SMA antenna","match E32 SMA connector"),
          ("PSU",1,"Regulated 5V 2A supply","not connected directly to vehicle 12/24V"),
          ("H1-H4",8,"M3 screws","4 for PCB posts, 4 for lid; length verified after trial print")]
    with (OUT/"BOM.csv").open("w",newline="",encoding="utf-8-sig") as f:
        writer=csv.writer(f);writer.writerow(["Reference","Quantity","Part","Notes"]);writer.writerows(rows)

if __name__=="__main__": generate()
