import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {encode,decode} from '../../protocol.mjs';
const $=id=>document.getElementById(id),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(43,1,1,2500);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x101d23);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;$('three-host').appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=70;controls.maxDistance=1200;
scene.add(new THREE.HemisphereLight(0xe6fff1,0x304758,3));for(const p of [[-200,400,200],[250,200,-150]]){const l=new THREE.DirectionalLight(0xffffff,3);l.position.set(...p);scene.add(l);}
const material=(color,metalness=0)=>new THREE.MeshStandardMaterial({color,metalness,roughness:.38});const silver=material('#a8b9bb',.85),dark=material('#20363c',.25),gold=material('#c5aa68',.7),green=material('#1b725c');
function cube(w,h,d,position,mat,parent=scene){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(...position);parent.add(m);return m;}
function rod(a,b,r,mat,parent=scene){a=new THREE.Vector3(...a);b=new THREE.Vector3(...b);const dir=b.clone().sub(a),m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,dir.length(),16),mat);m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),dir.normalize());parent.add(m);return m;}
function label(text,position,color='#d6e9df',size=34,parent=scene){const cv=document.createElement('canvas');cv.width=768;cv.height=96;const ctx=cv.getContext('2d');ctx.font='30px Arial';ctx.fillStyle=color;ctx.textAlign='center';ctx.fillText(text,384,60);const tx=new THREE.CanvasTexture(cv);tx.colorSpace=THREE.SRGBColorSpace;const m=new THREE.Sprite(new THREE.SpriteMaterial({map:tx,transparent:true,depthWrite:false}));m.position.set(...position);m.scale.set(size,size/8,1);parent.add(m);return m;}
const antenna=new THREE.Group();antenna.name='RX-01_433MHz_antenna_mm';antenna.userData={units:'millimetres',frequencyMHz:433,quarterWaveMm:299792458/(433e6)*1000/4,status:'geometric concept; RF tuning required'};
// Exportable geometry: feed at origin; real millimetre dimensions, not scene scaling.
rod([0,0,0],[0,173.1,0],1.5,silver,antenna);rod([0,-12,0],[0,0,0],5,dark,antenna);rod([0,-17,0],[0,-12,0],3,gold,antenna);
for(let i=0;i<4;i++){const a=i*Math.PI/2;rod([0,0,0],[122.4*Math.cos(a),-122.4,122.4*Math.sin(a)],1.3,silver,antenna);}
const station=new THREE.Group();scene.add(station);station.position.set(100,0,15);antenna.scale.setScalar(.55);antenna.position.y=104;station.add(antenna);
rod([0,0,0],[0,95,0],3,dark,station);cube(64,28,48,[0,16,0],dark,station);cube(60,2,44,[0,31,0],silver,station);cube(28,1,24,[0,33,0],green,station);cube(19,5,16,[0,36,0],silver,station);label('RX-01 / 433 MHz',[100,-13,15],'#d6bc79',190);
const cable=new THREE.CatmullRomCurve3([new THREE.Vector3(100,94,15),new THREE.Vector3(116,77,17),new THREE.Vector3(123,45,19),new THREE.Vector3(114,34,20)]);scene.add(new THREE.Mesh(new THREE.TubeGeometry(cable,30,1.5,8,false),dark));
const trackers=[{id:2,pos:[-125,12,-55],lat:51.128207,lon:71.430411},{id:3,pos:[-75,12,65],lat:51.132405,lon:71.438102},{id:4,pos:[20,12,-100],lat:51.124811,lon:71.422703}];
for(const t of trackers){t.point=new THREE.Vector3(...t.pos);t.seq=0;t.received=0;const g=new THREE.Group();g.position.copy(t.point);scene.add(g);cube(39,3,25,[0,0,0],green,g);cube(13,2,12,[-9,2,-3],material('#d6c9a4'),g);cube(10,2,8,[5,2,2],dark,g);cube(9,3,13,[13,2,-3],silver,g);rod([18,2,-5],[18,17,-5],.65,dark,g);label('AT-02 / '+t.id,[t.pos[0],-10,t.pos[2]],'#b2d2c0',160);const node=document.createElement('div');node.className='device';node.id='device-'+t.id;node.innerHTML=`<b>Трекер ${t.id}</b> <span>· ожидание</span><small>— координаты ещё не получены —</small>`;$('devices').appendChild(node);}
const satellites=[[-150,235,-90],[-35,275,90],[90,260,-120],[145,230,85]];
for(let i=0;i<satellites.length;i++){const g=new THREE.Group();g.position.set(...satellites[i]);g.rotation.z=(i-1.5)*.13;scene.add(g);cube(12,12,12,[0,0,0],silver,g);for(const x of [-19,19]){cube(22,1,14,[x,0,0],material('#326081',.3),g);for(const z of [-4,0,4])rod([x-10,1,z],[x+10,1,z],.15,silver,g);}label('GPS '+(i+1),[satellites[i][0],satellites[i][1]+18,satellites[i][2]],'#80c6b0',170);}
const grid=new THREE.GridHelper(550,28,0x38564f,0x213b38);grid.position.y=-4;scene.add(grid);
const waves=new THREE.Group();scene.add(waves);const particles=[];
function path(a,b,color){const p=new THREE.Vector3(...a),q=new THREE.Vector3(...b),line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([p,q]),new THREE.LineBasicMaterial({color,transparent:true,opacity:.13}));waves.add(line);const dots=[];for(let i=0;i<3;i++){const m=new THREE.Mesh(new THREE.SphereGeometry(1.5,10,10),new THREE.MeshBasicMaterial({color}));waves.add(m);dots.push(m);}return {p,q,dots,line};}
for(const t of trackers){t.gps=satellites.map(p=>path(p,t.pos,0x6be2bb));t.radio=path(t.pos,[100,104,15],0xefc97e);t.rings=[];for(let i=0;i<3;i++){const m=new THREE.Mesh(new THREE.TorusGeometry(1,.035,6,80),new THREE.MeshBasicMaterial({color:0xecc477,transparent:true,opacity:.5,depthWrite:false}));m.rotation.x=Math.PI/2;m.position.copy(t.point);waves.add(m);t.rings.push(m);}}
let running=true,time=0,last=performance.now(),total=0,mode='network';const cycle=9;
function receive(t){const wire=encode({deviceId:t.id,seq:t.seq++ & 65535,fix:true,lat:t.lat,lon:t.lon,altM:347,speedKmh:22,sats:9,hdop:.9});const parsed=decode(wire);if(!parsed)return;t.received++;total++;const n=$('device-'+t.id);n.classList.add('fresh');n.querySelector('span').textContent=`· ${t.received} пак.`;n.querySelector('small').textContent=`${t.lat.toFixed(6)} N / ${t.lon.toFixed(6)} E`;$('count').textContent=total+' пакетов';$('packet').textContent=wire.trim();$('packet-status').textContent='RX / ТРЕКЕР '+t.id;$('checksum').textContent='Контрольная сумма проверена · пакет принят';}
function animate(dt){if(running)time+=dt*Number($('speed').value);const phase=time%cycle;
 const stage=phase<3?0:phase<4?1:phase<7?2:3;const texts=['GPS / ПРИЁМ СИГНАЛОВ','FIX / КООРДИНАТЫ ВЫЧИСЛЕНЫ','433 MHz / ПЕРЕДАЧА ДАННЫХ','RX / ПАКЕТЫ ПРИНЯТЫ'];$('phase').textContent=texts[stage];['gps-stage','fix-stage','tx-stage','rx-stage'].forEach((id,i)=>$(id).classList.toggle('on',i===stage));
 trackers.forEach((t,i)=>{for(const p of t.gps){p.line.visible=stage===0;for(let j=0;j<p.dots.length;j++){const m=p.dots[j];m.visible=stage===0;m.position.lerpVectors(p.p,p.q,(time*.55+j/3)%1);}}
 const start=4+i*.8,progress=(phase-start)/1.1,active=progress>=0&&progress<1;t.radio.line.visible=active;t.radio.dots.forEach((m,j)=>{m.visible=active&&j===0;m.position.lerpVectors(t.radio.p,t.radio.q,THREE.MathUtils.clamp(progress,0,1));});t.rings.forEach((m,j)=>{m.visible=active;const u=(Math.max(0,phase-start)*1.5+j/3)%1;m.scale.setScalar(8+u*150);m.material.opacity=(1-u)*.55;});
 const index=Math.floor(time/cycle);if(phase>=start+1.1&&t.lastCycle!==index){t.lastCycle=index;receive(t);}if(phase<start)$('device-'+t.id).classList.remove('fresh');
 });waves.visible=$('waves').checked&&mode==='network';}
function home(){mode='network';camera.position.set(400,310,470);controls.target.set(0,110,0);controls.update();$('network').classList.add('active');$('antenna-view').classList.remove('active');}
$('network').onclick=home;$('home').onclick=home;$('antenna-view').onclick=()=>{mode='antenna';camera.position.set(250,170,210);controls.target.set(100,115,15);controls.update();$('network').classList.remove('active');$('antenna-view').classList.add('active');};
$('play').onclick=()=>{running=!running;$('play').textContent=running?'Ⅱ Пауза':'▶ Продолжить';};
$('reset').onclick=()=>{time=0;total=0;for(const t of trackers){t.lastCycle=undefined;t.received=0;t.seq=0;const n=$('device-'+t.id);n.classList.remove('fresh');n.querySelector('span').textContent='· ожидание';n.querySelector('small').textContent='— координаты ещё не получены —';}$('count').textContent='0 пакетов';$('packet').textContent='Приёмник слушает канал 433 МГц…';$('packet-status').textContent='ОЖИДАНИЕ ПЕРЕДАЧИ';$('checksum').textContent='Демонстрационные координаты / формат протокола V2';};
$('download').onclick=async e=>{e.preventDefault();const model=antenna.clone();model.scale.setScalar(.001);model.userData={...model.userData,units:'metres',sourceGeometryUnits:'millimetres'};model.position.set(0,0,0);const binary=await new GLTFExporter().parseAsync(model,{binary:true});const url=URL.createObjectURL(new Blob([binary],{type:'model/gltf-binary'})),a=document.createElement('a');a.href=url;a.download='RX-01-antenna-433MHz.glb';a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);};
const resize=()=>{const r=$('three-host').getBoundingClientRect();renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();};new ResizeObserver(resize).observe($('three-host'));home();resize();renderer.setAnimationLoop(()=>{const now=performance.now();animate(Math.min((now-last)/1000,.1));last=now;controls.update();renderer.render(scene,camera);});
window.receiverDemo={scene,renderer,antenna,trackers,get time(){return time},get received(){return total},advance:seconds=>{time+=seconds;animate(0);},get running(){return running}};
